// Hierarchy Builder
//
// var employees = [{
//     id: 1,
//         name: 'Mike'
//         }, {
//             id: 2,
//                 name: 'Alice'
//                 }, {
//                     id: 3,
//                         name: 'Bob',
//                             manager: 2
//                             }, {
//                                 id: 4,
//                                     name: 'Ken',
//                                         manager: 3
//                                         }, {
//                                             id: 5,
//                                                 name: 'Alex',
//                                                     manager: 4
//                                                     }]
//
//                                                     function buildHierarchy(list, employee) {
//                                                         if (!list) return;
//                                                             if (list && employee) {
//                                                                     let manager = list.find(function(el) {
//                                                                                      
//                                                                                                  return (el && (el.id === employee.manager)) || false;
//                                                                                                                  
//                                                                                                                          });
//                                                                                                                                
//                                                                                                                                      manager && (manager.children || (manager.children = [])) && manager.children.push(employee) && (delete employee.manager);
//                                                                                                                                            return
//                                                                                                                                                  
//                                                                                                                                                      }
//                                                                                                                                                          var newList = [], manager;
//                                                                                                                                                              
//                                                                                                                                                                  var len = list.length;
//                                                                                                                                                                      for (var i =0; i< len; i++) {
//                                                                                                                                                                              if (!list[i].manager) {
//                                                                                                                                                                                           //no manager property case. Basically C title employee
//                                                                                                                                                                                                        newList.push(list[i]);   
//                                                                                                                                                                                                                } else {
//                                                                                                                                                                                                                           //has manager property, so look for its manager
//                                                                                                                                                                                                                                       manager = newList.find(function(el) {
//                                                                                                                                                                                                                                                        //found the manager
//                                                                                                                                                                                                                                                                        // console.log(list);
//                                                                                                                                                                                                                                                                                        // console.log("el", el, "manager", list[i]);
//                                                                                                                                                                                                                                                                                                         return (list[i].manager && (list[i].manager === el.id)) || false;
//                                                                                                                                                                                                                                                                                                                         
//                                                                                                                                                                                                                                                                                                                                     });
//                                                                                                                                                                                                                                                                                                                                                 
//                                                                                                                                                                                                                                                                                                                                                             if (manager) {
//                                                                                                                                                                                                                                                                                                                                                                             //manager found
//                                                                                                                                                                                                                                                                                                                                                                                               if (!manager.children) {
//                                                                                                                                                                                                                                                                                                                                                                                                                   manager.children = [];
//                                                                                                                                                                                                                                                                                                                                                                                                                                     }
//                                                                                                                                                                                                                                                                                                                                                                                                                                                     delete list[i].manager;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                     manager.children.push(list[i]);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 } else {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //manager is not at level 0
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 let len2 = newList.length;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 for(var j=0; j < len2; j++) {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if(newList[j].children) {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             buildHierarchy(newList[j].children, list[i]);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }// end of for i
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return newList;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 var result = buildHierarchy(employees);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 console.log(JSON.stringify(result));
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // Output
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // [{
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //     id: 1,
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //     name: 'Mike'
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // }, {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //     id: 2,
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //     name: 'Alice',
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //     children: [{
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //         id: 3,
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //         name: 'Bob',
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //         children: [{
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //             id: 4,
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //             name: 'Ken',
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //             children: [{
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //                 id: 5,
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //                 name: 'Alex'
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //             }]
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //         }]
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //     }]
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // }]
//
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // Mike
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // Alice
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //     Bob
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //         Ken
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //             Alex
